<?php


namespace Plugin\ResizeImage4\Tests\Form\Admin;


use Eccube\Tests\Form\Type\AbstractTypeTestCase;
use Plugin\ResizeImage4\Form\Type\Admin\AmazonS3Type;

class AmazonS3TypeTest extends AbstractTypeTestCase
{
    protected $form;

    protected $formData = [
        'enabled' => false,
        'access_key_id' => '',
        'secret_access_key' => '',
        'bucket' => '',
        'region' => '',
        'cache_control' => ''
    ];

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->form = $this->formFactory
            ->createBuilder(AmazonS3Type::class, null, [
                'csrf_protection' => false
            ])
            ->getForm();
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testS3無効の場合は他の項目が空でも大丈夫()
    {
        $this->form->submit($this->formData);
        self::assertTrue($this->form->isValid());
    }

    public function testS3有効の場合は他の項目が空だとエラー()
    {
        $this->formData['enabled'] = true;
        $this->form->submit($this->formData);
        self::assertFalse($this->form->isValid());
    }

    public function testCacheControlが1以上だったらOK()
    {
        $this->formData['cache_control'] = 1;
        $this->form->submit($this->formData);
        self::assertTrue($this->form->isValid());
    }

    public function testCacheControlが0だったら駄目()
    {
        $this->formData['cache_control'] = 0;
        $this->form->submit($this->formData);
        self::assertFalse($this->form->isValid());
    }

    public function testCacheControlが0未満だったら駄目()
    {
        $this->formData['cache_control'] = -1;
        $this->form->submit($this->formData);
        self::assertFalse($this->form->isValid());
    }

    public function testCacheControlが数値じゃなかったらエラー()
    {
        $this->formData['cache_control'] = 'sss';
        $this->form->submit($this->formData);
        self::assertFalse($this->form->isValid());
    }
}
