<?php


namespace Plugin\ResizeImage4\Tests\Form\Admin;


use Eccube\Tests\Form\Type\AbstractTypeTestCase;
use Plugin\ResizeImage4\Form\Type\Admin\AmazonS3\BucketType;

class AmazonS3TypeTest extends AbstractTypeTestCase
{
    protected $form;

    protected $formData = [
        'bucket' => 'dummy',
    ];

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->form = $this->formFactory
            ->createBuilder(BucketType::class, null, [
                'csrf_protection' => false
            ])
            ->getForm();
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test正常データ()
    {
        $this->form->submit($this->formData);
        self::assertTrue($this->form->isValid());
    }
}
