#
# This file is part of ResizeImage4
#
# Copyright(c) Akira Kurozumi <info@a-zumi.net>
#
# https://a-zumi.net
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

parameters:
  env(AWS_S3_ENABLED): 0
  env(AWS_S3_BUCKET): ''

liip_imagine:
  resolvers:
    default:
      web_path:
        web_root: '%kernel.project_dir%'
        cache_prefix: 'media/cache'

    aws_s3_resolver:
      aws_s3:
        bucket: '%env(AWS_S3_BUCKET)%' #バケット名を設定してください
        client_config:
          version: '2006-03-01'
          region: 'ap-northeast-1'
        get_options:
          Scheme: https
        put_options:
          CacheControl: "max-age=86400"

  loaders:
    default:
      filesystem:
        data_root: '%kernel.project_dir%'

  filter_sets:
    cache: ~

    # the name of the "filter set"
    resize:
      # cache: aws_s3_resolver # AWS S3を利用したい場合コメントアウトしてください
