#
# This file is part of ResizeImage4
#
# Copyright(c) Akira Kurozumi <info@a-zumi.net>
#
# https://a-zumi.net
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

liip_imagine :
  resolvers :
    default :
      web_path :
        web_root: '%kernel.project_dir%'
        cache_prefix: 'media/cache'

  loaders:
    default:
      filesystem:
        data_root: '%kernel.project_dir%'

  filter_sets :
    cache : ~

    # the name of the "filter set"
    resize :
