#
# This file is part of ResizeImage4
#
# Copyright(c) Akira Kurozumi <info@a-zumi.net>
#
# https://a-zumi.net
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

parameters:
  env(AWS_S3_ENABLED): 0
  env(AWS_S3_BUCKET): ''
  env(AWS_S3_REGION): 'ap-northeast-1'
  env(AWS_S3_CACHE_CONTROL): '86400'

  aws_s3_region: '%env(AWS_S3_REGION)%'
  aws_s3_cache_control: '%env(AWS_S3_CACHE_CONTROL)%'
  aws_s3_version: '2006-03-01'

liip_imagine:
  resolvers:
    default:
      web_path:
        web_root: '%kernel.project_dir%'
        cache_prefix: 'media/cache'

    aws_s3_resolver:
      aws_s3:
        bucket: '%env(AWS_S3_BUCKET)%'
        client_config:
          version: '%aws_s3_version%'
          region: '%env(AWS_S3_REGION)%'
        get_options:
          Scheme: https
        put_options:
          CacheControl: "max-age=%env(AWS_S3_CACHE_CONTROL)%"

  loaders:
    default:
      filesystem:
        data_root: '%kernel.project_dir%'

  filter_sets:
    cache: ~

    # the name of the "filter set"
    resize:
      # cache: aws_s3_resolver


services:
  Aws\S3\S3Client:
    factory: ['Plugin\ResizeImage4\Factory\AmazonS3ClientFactory', 'create']
    arguments:
      -
        version: '%aws_s3_version%'
        region: '%env(AWS_S3_REGION)%'
