#
# This file is part of ResizeImage
#
# Copyright(c) Akira Kurozumi <info@a-zumi.net>
#
# https://a-zumi.net
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

parameters:
  env(AWS_ACCESS_KEY_ID): ''
  env(AWS_SECRET_ACCESS_KEY): ''
  env(AWS_S3_REGION): 'ap-northeast-1'
  env(AWS_S3_BUCKET): ''
  env(AWS_S3_ENABLED): 0
  env(AWS_S3_CACHE_CONTROL): '86400'

  amazon.s3.key: '%env(AWS_ACCESS_KEY_ID)%'
  amazon.s3.secret: '%env(AWS_SECRET_ACCESS_KEY)%'
  amazon.s3.bucket: '%env(AWS_S3_BUCKET)%'
  amazon.s3.region: '%env(AWS_S3_REGION)%'
  amazon.s3.version: '2006-03-01'
  amazon.s3.cache_control: '%env(AWS_S3_CACHE_CONTROL)%'

liip_imagine:
  resolvers:
    default:
      web_path:
        web_root: '%kernel.project_dir%'
        cache_prefix: 'media/cache'

    aws_s3_resolver:
      aws_s3:
        client_config:
          credentials:
            key: '%amazon.s3.key%'
            secret: '%amazon.s3.secret%'
          region: '%amazon.s3.region%'
          version: '%amazon.s3.version%'
        bucket: '%amazon.s3.bucket%'
        get_options:
          Scheme: https
        put_options:
          CacheControl: "max-age=%amazon.s3.cache_control%"

  loaders:
    default:
      filesystem:
        data_root: '%kernel.project_dir%'

  filter_sets:
    cache: ~

    # the name of the "filter set"
    resize:
    # cache: aws_s3_resolver


services:
  plugin.resize_image.amazon_s3:
    class: Aws\S3\S3Client
    factory: [Aws\S3\S3Client, factory]
    arguments:
        -
          credentials: { key: "%amazon.s3.key%", secret: "%amazon.s3.secret%" }
          version: '%amazon.s3.version%'
          region: '%amazon.s3.region%'

  plugin.resize_image.imagine.cache.resolver.aws_s3_resolver:
    class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
    arguments:
      - "@plugin.resize_image.amazon_s3"
      - "%amazon.s3.bucket%"
    tags:
      - { name: "liip_imagine.cache.resolver", resolver: "aws_s3_resolver" }

  Aws\S3\S3Client:
    factory: [ 'Plugin\ResizeImage42\Factory\AmazonS3ClientFactory', 'create' ]
    arguments:
      - version: '%amazon.s3.version%'
        region: '%amazon.s3.region%'
