name: CI/CD for EC-CUBE4 Plugin with Composer:v1
on: [workflow_dispatch, pull_request]
jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        eccube-versions: ['4.0','4.1']
        php-versions: [7.1,7.2,7.3,7.4]
        database: [mysql, pgsql]
        include:
          - database: mysql
            database_url: mysql://root:root@127.0.0.1:3306/eccube_db
            database_server_version: 5
          - database: pgsql
            database_url: postgres://postgres:password@127.0.0.1:5432/eccube_db
            database_server_version: 11

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: eccube_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: eccube_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@master #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, mysql, intl
          tools: composer:v1

      - name: Clone EC-CUBE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tar cvzf $HOME/${{ github.event.repository.name }}.tar.gz ./*
          git clone  https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/EC-CUBE/ec-cube.git -b ${{ matrix.eccube-versions }} --depth=1

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run : |
          cd ec-cube
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
          composer require --dev kiy0taka/eccube4-test-fixer

      - name: Setup EC-CUBE
        run: |
          cd ec-cube
          bin/console doctrine:schema:create
          bin/console eccube:fixtures:load
        env:
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}

      - name: Install Plugin
        run: |
          cd ec-cube
          bin/console eccube:plugin:install --path=$HOME/${{ github.event.repository.name }}.tar.gz
          bin/console cache:clear --no-warmup
          bin/console eccube:plugin:enable --code=${{ github.event.repository.name }}
        env:
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}

      - name: Run Tests for EC-CUBE4.0
        if: matrix.eccube-versions == '4.0'
        run: |
          cd ec-cube
          find app/Plugin/${{ github.event.repository.name }}/Tests -name "*Test.php" | while read TESTCASE
          do
            bin/phpunit --include-path vendor/kiy0taka/eccube4-test-fixer/src --loader 'Eccube\PHPUnit\Loader\Eccube4CompatTestSuiteLoader' ${TESTCASE}
          done
        env:
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}

      - name: Run Tests
        if: matrix.eccube-versions != '4.0'
        run: |
          cd ec-cube
          bin/phpunit app/Plugin/${{ github.event.repository.name }}/Tests
        env:
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}

      - name: Update Plugin
        run: |
          cd ec-cube
          bin/console eccube:plugin:update ${{ github.event.repository.name }}
        env:
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}

      - name: Uninstall Plugin
        run: |
          cd ec-cube
          bin/console eccube:plugin:uninstall --code=${{ github.event.repository.name }}
        env:
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
