name: E2E test for EC-CUBE4 Plugin
on: [workflow_dispatch, pull_request]
env:
  PLUGIN_CODE: ResizeImage42
jobs:
  selenium:
    name: Selenium
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        eccube-versions: ['4.2', '4.3']
        php-versions: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]
        exclude:
          - eccube-versions: 4.2
            php-versions: 8.2
          - eccube-versions: 4.2
            php-versions: 8.3
          - eccube-versions: 4.3
            php-versions: 7.4
          - eccube-versions: 4.3
            php-versions: 8.0

    steps:
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@master #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, mysql, intl, :xdebug
          tools: composer:v2

      - name: Checkout EC-CUBE
        uses: actions/checkout@v4
        with:
          repository: EC-CUBE/ec-cube
          ref: ${{ matrix.eccube-versions }}

      - name: composer install
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader
          composer require liip/imagine-bundle
          composer require aws/aws-sdk-php

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: app/Plugin/${{ env.PLUGIN_CODE }}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup EC-CUBE and Plugin
        run: |
          bin/console e:i
          bin/console eccube:plugin:install --code ${{ env.PLUGIN_CODE }}
          bin/console eccube:plugin:enable --code ${{ env.PLUGIN_CODE }}

      - name: Start PHP Development Server
        run: php -S localhost:8000 &

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Python dependencies
        run: |
          cd app/Plugin/${{ env.PLUGIN_CODE }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: E2E Test
        run: |
          cd app/Plugin/${{ env.PLUGIN_CODE }}/selenium
          python -m unittest discover -v
